In [1]:
%ls

 adult.csv                   coches.csv             README.md
 airline_data.csv            cwurData.csv           reg_data.csv
 antropometria00.csv         data.csv               requirements.txt
 antropometria-dataset.csv   datasets/              sample_pivot.csv
 Book3.csv                   headbrain.csv          tips.csv
 Canada.xlsx                 mic2.xlsx             'Untitled Folder'/
 Cartwheeldata.csv           movies.csv             weight-height.csv
 census.csv                  nhanes_2015_2016.csv
 Clase3-act2.ipynb           pokemon.csv

In [2]:
%ls datasets/

adult.csv                  census.csv     nhanes_2015_2016.csv
airline_data.csv           coches.csv     pokemon.csv
antropometria00.csv        cwurData.csv   reg_data.csv
antropometria-dataset.csv  data.csv       sample_pivot.csv
Book3.csv                  headbrain.csv  tips.csv
Canada.xlsx                mic2.xlsx      weight-height.csv
Cartwheeldata.csv          movies.csv

In [3]:
import pandas as pd
import numpy as np

In [4]:
df=pd.read_csv('datasets/airline_data.csv',
               low_memory=False
              )
df.head(2)

,Unnamed: 0,Year,Quarter,Month,DayofMonth,DayOfWeek,FlightDate,Reporting_Airline,DOT_ID_Reporting_Airline,IATA_CODE_Reporting_Airline,...,Div4WheelsOff,Div4TailNum,Div5Airport,Div5AirportID,Div5AirportSeqID,Div5WheelsOn,Div5TotalGTime,Div5LongestGTime,Div5WheelsOff,Div5TailNum
0,1295781,1998,2,4,2,4,1998-04-02,AS,19930,AS,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1125375,2013,2,5,13,1,2013-05-13,EV,20366,EV,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [5]:
x=df.columns.tolist()
x.sort()
x

['ActualElapsedTime',
 'AirTime',
 'ArrDel15',
 'ArrDelay',
 'ArrDelayMinutes',
 'ArrTime',
 'ArrTimeBlk',
 'ArrivalDelayGroups',
 'CRSArrTime',
 'CRSDepTime',
 'CRSElapsedTime',
 'CancellationCode',
 'Cancelled',
 'CarrierDelay',
 'DOT_ID_Reporting_Airline',
 'DayOfWeek',
 'DayofMonth',
 'DepDel15',
 'DepDelay',
 'DepDelayMinutes',
 'DepTime',
 'DepTimeBlk',
 'DepartureDelayGroups',
 'Dest',
 'DestAirportID',
 'DestAirportSeqID',
 'DestCityMarketID',
 'DestCityName',
 'DestState',
 'DestStateFips',
 'DestStateName',
 'DestWac',
 'Distance',
 'DistanceGroup',
 'Div1Airport',
 'Div1AirportID',
 'Div1AirportSeqID',
 'Div1LongestGTime',
 'Div1TailNum',
 'Div1TotalGTime',
 'Div1WheelsOff',
 'Div1WheelsOn',
 'Div2Airport',
 'Div2AirportID',
 'Div2AirportSeqID',
 'Div2LongestGTime',
 'Div2TailNum',
 'Div2TotalGTime',
 'Div2WheelsOff',
 'Div2WheelsOn',
 'Div3Airport',
 'Div3AirportID',
 'Div3AirportSeqID',
 'Div3LongestGTime',
 'Div3TailNum',
 'Div3TotalGTime',
 'Div3WheelsOff',
 'Div3WheelsOn',
 'Div4Airport',
 'Div4AirportID',
 'Div4AirportSeqID',
 'Div4LongestGTime',
 'Div4TailNum',
 'Div4TotalGTime',
 'Div4WheelsOff',
 'Div4WheelsOn',
 'Div5Airport',
 'Div5AirportID',
 'Div5AirportSeqID',
 'Div5LongestGTime',
 'Div5TailNum',
 'Div5TotalGTime',
 'Div5WheelsOff',
 'Div5WheelsOn',
 'DivActualElapsedTime',
 'DivAirportLandings',
 'DivArrDelay',
 'DivDistance',
 'DivReachedDest',
 'Diverted',
 'FirstDepTime',
 'FlightDate',
 'Flight_Number_Reporting_Airline',
 'Flights',
 'IATA_CODE_Reporting_Airline',
 'LateAircraftDelay',
 'LongestAddGTime',
 'Month',
 'NASDelay',
 'Origin',
 'OriginAirportID',
 'OriginAirportSeqID',
 'OriginCityMarketID',
 'OriginCityName',
 'OriginState',
 'OriginStateFips',
 'OriginStateName',
 'OriginWac',
 'Quarter',
 'Reporting_Airline',
 'SecurityDelay',
 'Tail_Number',
 'TaxiIn',
 'TaxiOut',
 'TotalAddGTime',
 'Unnamed: 0',
 'WeatherDelay',
 'WheelsOff',
 'WheelsOn',
 'Year']

In [6]:
df['DepartureDelayGroups'].max()

12.0

In [7]:
df['DepDelay']

0        0.0
1       -6.0
2       33.0
3       24.0
4       -9.0
        ...
9437    -4.0
9438    21.0
9439     0.0
9440    -4.0
9441     0.0
Name: DepDelay, Length: 9442, dtype: float64

In [8]:
df['DepDelay'].min()

-23.0

In [9]:
df['DepDelay'].max()

988.0

In [10]:
df.groupby(['DepDelay','DepartureDelayGroups']).size()

DepDelay  DepartureDelayGroups
-23.0     -2.0                    1
-19.0     -2.0                    2
-18.0     -2.0                    1
-17.0     -2.0                    3
-16.0     -2.0                    6
                                 ..
 403.0     12.0                   1
 460.0     12.0                   1
 600.0     12.0                   1
 732.0     12.0                   1
 988.0     12.0                   1
Length: 224, dtype: int64

In [11]:
pd.pivot_table(df,
               index=['Year'],
               values='DepDelay',
               columns='DepartureDelayGroups',
               aggfunc='sum',
               margins= True
              )

DepartureDelayGroups,-2.0,-1.0,0.0,1.0,2.0,3.0,4.0,5.0,6.0,7.0,8.0,9.0,10.0,11.0,12.0,All
Year,,,,,,,,,,,,,,,,
1987,NaN,-20.0,81.0,145.0,36.0,97.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,339.0
1988,NaN,-64.0,385.0,408.0,263.0,149.0,126.0,245.0,98.0,109.0,NaN,NaN,151.0,179.0,NaN,2049.0
1989,NaN,-84.0,450.0,417.0,231.0,196.0,335.0,155.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1700.0
1990,NaN,-135.0,350.0,383.0,112.0,49.0,268.0,NaN,NaN,108.0,122.0,NaN,NaN,NaN,NaN,1257.0
1991,NaN,-120.0,425.0,291.0,361.0,209.0,62.0,88.0,NaN,107.0,NaN,NaN,NaN,NaN,NaN,1423.0
1992,NaN,-140.0,329.0,326.0,145.0,164.0,NaN,NaN,NaN,NaN,NaN,NaN,158.0,NaN,NaN,982.0
1993,NaN,-161.0,381.0,267.0,271.0,305.0,70.0,NaN,99.0,NaN,NaN,NaN,NaN,NaN,308.0,1540.0
1994,NaN,-120.0,402.0,337.0,295.0,158.0,62.0,81.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1215.0
1995,NaN,-183.0,490.0,433.0,256.0,399.0,133.0,159.0,NaN,222.0,NaN,NaN,NaN,NaN,NaN,1909.0
1996,NaN,-177.0,427.0,357.0,365.0,412.0,330.0,85.0,96.0,NaN,NaN,146.0,158.0,174.0,364.0,2737.0
1997,NaN,-224.0,387.0,284.0,264.0,200.0,321.0,167.0,103.0,225.0,NaN,NaN,161.0,170.0,241.0,2299.0
1998,NaN,-263.0,354.0,350.0,302.0,264.0,64.0,NaN,199.0,NaN,258.0,NaN,NaN,NaN,NaN,1528.0
1999,-18.0,-327.0,381.0,352.0,341.0,361.0,332.0,171.0,NaN,110.0,NaN,NaN,NaN,165.0,238.0,2106.0
2000,NaN,-323.0,416.0,444.0,533.0,256.0,478.0,170.0,NaN,116.0,NaN,294.0,NaN,177.0,998.0,3559.0
2001,NaN,-498.0,333.0,205.0,764.0,196.0,342.0,162.0,90.0,106.0,NaN,149.0,156.0,165.0,214.0,2384.0
2002,NaN,-546.0,234.0,392.0,334.0,307.0,200.0,80.0,99.0,NaN,NaN,140.0,NaN,NaN,180.0,1420.0
2003,NaN,-783.0,193.0,393.0,237.0,247.0,203.0,162.0,NaN,117.0,121.0,281.0,NaN,NaN,NaN,1171.0
2004,NaN,-743.0,252.0,359.0,403.0,272.0,451.0,253.0,195.0,110.0,124.0,140.0,308.0,NaN,207.0,2331.0
2005,NaN,-699.0,384.0,510.0,503.0,661.0,579.0,802.0,104.0,NaN,124.0,NaN,160.0,NaN,1000.0,4128.0
2006,NaN,-773.0,340.0,491.0,381.0,467.0,594.0,79.0,290.0,108.0,128.0,285.0,322.0,NaN,464.0,3176.0
2007,NaN,-715.0,523.0,624.0,432.0,626.0,597.0,87.0,478.0,111.0,495.0,149.0,462.0,172.0,396.0,4437.0
2008,-55.0,-766.0,383.0,498.0,350.0,152.0,327.0,251.0,573.0,226.0,248.0,143.0,155.0,171.0,582.0,3238.0
2009,NaN,-907.0,364.0,415.0,409.0,209.0,201.0,335.0,685.0,350.0,NaN,NaN,159.0,168.0,780.0,3168.0
2010,NaN,-932.0,394.0,525.0,549.0,368.0,200.0,235.0,298.0,219.0,125.0,NaN,150.0,NaN,990.0,3121.0
2011,-19.0,-776.0,306.0,333.0,257.0,257.0,208.0,407.0,104.0,576.0,NaN,143.0,471.0,177.0,181.0,2625.0
2012,-16.0,-759.0,244.0,475.0,405.0,212.0,282.0,172.0,90.0,110.0,383.0,NaN,NaN,172.0,1577.0,3347.0
2013,-17.0,-750.0,326.0,555.0,513.0,530.0,338.0,237.0,97.0,107.0,132.0,140.0,158.0,NaN,460.0,2826.0
2014,-16.0,-750.0,360.0,683.0,380.0,458.0,402.0,655.0,380.0,452.0,121.0,139.0,NaN,NaN,431.0,3695.0
2015,-16.0,-716.0,337.0,535.0,516.0,404.0,264.0,327.0,98.0,448.0,130.0,138.0,150.0,NaN,1071.0,3686.0
2016,NaN,-681.0,218.0,424.0,461.0,301.0,61.0,256.0,281.0,232.0,367.0,NaN,NaN,168.0,185.0,2273.0
2017,NaN,-776.0,232.0,434.0,250.0,276.0,333.0,78.0,483.0,NaN,NaN,141.0,305.0,170.0,1127.0,3053.0
2018,-50.0,-986.0,264.0,467.0,357.0,360.0,339.0,161.0,296.0,339.0,253.0,431.0,NaN,171.0,417.0,2819.0
2019,-19.0,-1125.0,374.0,532.0,590.0,482.0,394.0,399.0,200.0,115.0,131.0,NaN,164.0,NaN,522.0,2759.0
2020,NaN,-314.0,54.0,44.0,108.0,57.0,135.0,83.0,NaN,NaN,NaN,140.0,NaN,NaN,NaN,307.0
All,-226.0,-17336.0,11373.0,13688.0,11974.0,10061.0,9031.0,6542.0,5436.0,4723.0,3262.0,2999.0,3748.0,2399.0,12933.0,80607.0

## function Lambda
#lambda  arguments : expression

In [12]:
x = lambda a: a + 2

In [13]:
x(5)

7

In [14]:
x = lambda a: a * 2+10

In [15]:
x(5)

20

In [16]:
y= lambda a, b: a+b-2

In [17]:
y(2,3)

3

In [18]:
z= lambda a=0,b=0,c=0 : a+b-2*c

In [19]:
import pandas as pd

In [20]:
df = pd.DataFrame(
    ['A+','A','A-','B+','B','B-','C+','C','C-','D+','D'],
    index =['excellent','excellent','excellent','good','good','good','ok','ok','ok','poor','poor'],
    columns=['Grades']
)
df

          Grades
excellent     A+
excellent      A
excellent     A-
good          B+
good           B
good          B-
ok            C+
ok             C
ok            C-
poor          D+
poor           D

In [21]:
type(df['Grades'])

pandas.core.series.Series

In [22]:
df['Grades'].astype('category')

excellent    A+
excellent     A
excellent    A-
good         B+
good          B
good         B-
ok           C+
ok            C
ok           C-
poor         D+
poor          D
Name: Grades, dtype: category
Categories (11, object): [A, A+, A-, B, ..., C+, C-, D, D+]

In [25]:
orded = pd.CategoricalDtype(
    categories=['D','D+','C-','C','C+','B-','B','B+','A-','A','A+'],
    ordered=True)
grades= df['Grades'].astype(orded)
print(grades)

excellent    A+
excellent     A
excellent    A-
good         B+
good          B
good         B-
ok           C+
ok            C
ok           C-
poor         D+
poor          D
Name: Grades, dtype: category
Categories (11, object): [D < D+ < C- < C ... B+ < A- < A < A+]