##   Clase 2: Data wrangling

In [1]:
pip install pandas

Requirement already satisfied: pandas in /srv/conda/envs/notebook/lib/python3.7/site-packages (1.3.5)
Requirement already satisfied: python-dateutil>=2.7.3 in /srv/conda/envs/notebook/lib/python3.7/site-packages (from pandas) (2.8.2)
Requirement already satisfied: pytz>=2017.3 in /srv/conda/envs/notebook/lib/python3.7/site-packages (from pandas) (2021.3)
Requirement already satisfied: numpy>=1.17.3 in /srv/conda/envs/notebook/lib/python3.7/site-packages (from pandas) (1.21.6)
Requirement already satisfied: six>=1.5 in /srv/conda/envs/notebook/lib/python3.7/site-packages (from python-dateutil>=2.7.3->pandas) (1.16.0)
Note: you may need to restart the kernel to use updated packages.

In [2]:
import pandas as pd
import numpy  as np

In [3]:
%ls datasets/

adult.csv                  census.csv     nhanes_2015_2016.csv
airline_data.csv           coches.csv     pokemon.csv
antropometria00.csv        cwurData.csv   reg_data.csv
antropometria-dataset.csv  data.csv       sample_pivot.csv
Book3.csv                  headbrain.csv  tips.csv
Canada.xlsx                mic2.xlsx      weight-height.csv
Cartwheeldata.csv          movies.csv

In [4]:
pip install xlrd

Requirement already satisfied: xlrd in /srv/conda/envs/notebook/lib/python3.7/site-packages (2.0.1)
Note: you may need to restart the kernel to use updated packages.

In [5]:
pip install openpyxl

Requirement already satisfied: openpyxl in /srv/conda/envs/notebook/lib/python3.7/site-packages (3.0.9)
Requirement already satisfied: et-xmlfile in /srv/conda/envs/notebook/lib/python3.7/site-packages (from openpyxl) (1.1.0)
Note: you may need to restart the kernel to use updated packages.

In [6]:
df= pd.read_excel ("datasets/Canada.xlsx",
                   sheet_name= "Canada by Citizenship",
                   skiprows= range(20),
                   skipfooter=2, 
                   engine="openpyxl"
                  )

In [7]:
df

,Type,Coverage,OdName,AREA,AreaName,REG,RegName,DEV,DevName,1980,...,2004,2005,2006,2007,2008,2009,2010,2011,2012,2013
0,Immigrants,Foreigners,Afghanistan,935,Asia,5501,Southern Asia,902,Developing regions,16,...,2978,3436,3009,2652,2111,1746,1758,2203,2635,2004
1,Immigrants,Foreigners,Albania,908,Europe,925,Southern Europe,901,Developed regions,1,...,1450,1223,856,702,560,716,561,539,620,603
2,Immigrants,Foreigners,Algeria,903,Africa,912,Northern Africa,902,Developing regions,80,...,3616,3626,4807,3623,4005,5393,4752,4325,3774,4331
3,Immigrants,Foreigners,American Samoa,909,Oceania,957,Polynesia,902,Developing regions,0,...,0,0,1,0,0,0,0,0,0,0
4,Immigrants,Foreigners,Andorra,908,Europe,925,Southern Europe,901,Developed regions,0,...,0,0,1,1,0,0,0,0,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
190,Immigrants,Foreigners,Viet Nam,935,Asia,920,South-Eastern Asia,902,Developing regions,1191,...,1816,1852,3153,2574,1784,2171,1942,1723,1731,2112
191,Immigrants,Foreigners,Western Sahara,903,Africa,912,Northern Africa,902,Developing regions,0,...,0,0,1,0,0,0,0,0,0,0
192,Immigrants,Foreigners,Yemen,935,Asia,922,Western Asia,902,Developing regions,1,...,124,161,140,122,133,128,211,160,174,217
193,Immigrants,Foreigners,Zambia,903,Africa,910,Eastern Africa,902,Developing regions,11,...,56,91,77,71,64,60,102,69,46,59
194,Immigrants,Foreigners,Zimbabwe,903,Africa,910,Eastern Africa,902,Developing regions,72,...,1450,615,454,663,611,508,494,434,437,407

In [8]:
df.columns

Index([    'Type', 'Coverage',   'OdName',     'AREA', 'AreaName',      'REG',
        'RegName',      'DEV',  'DevName',       1980,       1981,       1982,
             1983,       1984,       1985,       1986,       1987,       1988,
             1989,       1990,       1991,       1992,       1993,       1994,
             1995,       1996,       1997,       1998,       1999,       2000,
             2001,       2002,       2003,       2004,       2005,       2006,
             2007,       2008,       2009,       2010,       2011,       2012,
             2013],
      dtype='object')

In [9]:
df.head(2)

,Type,Coverage,OdName,AREA,AreaName,REG,RegName,DEV,DevName,1980,...,2004,2005,2006,2007,2008,2009,2010,2011,2012,2013
0,Immigrants,Foreigners,Afghanistan,935,Asia,5501,Southern Asia,902,Developing regions,16,...,2978,3436,3009,2652,2111,1746,1758,2203,2635,2004
1,Immigrants,Foreigners,Albania,908,Europe,925,Southern Europe,901,Developed regions,1,...,1450,1223,856,702,560,716,561,539,620,603

In [10]:
df.head(3)

,Type,Coverage,OdName,AREA,AreaName,REG,RegName,DEV,DevName,1980,...,2004,2005,2006,2007,2008,2009,2010,2011,2012,2013
0,Immigrants,Foreigners,Afghanistan,935,Asia,5501,Southern Asia,902,Developing regions,16,...,2978,3436,3009,2652,2111,1746,1758,2203,2635,2004
1,Immigrants,Foreigners,Albania,908,Europe,925,Southern Europe,901,Developed regions,1,...,1450,1223,856,702,560,716,561,539,620,603
2,Immigrants,Foreigners,Algeria,903,Africa,912,Northern Africa,902,Developing regions,80,...,3616,3626,4807,3623,4005,5393,4752,4325,3774,4331

In [11]:
pd.set_option("display.max_columns", None)

In [12]:
pd.set_option("display.max_rows", None)

In [13]:
df.info(verbose=False)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 195 entries, 0 to 194
Columns: 43 entries, Type to 2013
dtypes: int64(37), object(6)
memory usage: 65.6+ KB

In [14]:
df.shape

(195, 43)

In [15]:
df.columns

Index([    'Type', 'Coverage',   'OdName',     'AREA', 'AreaName',      'REG',
        'RegName',      'DEV',  'DevName',       1980,       1981,       1982,
             1983,       1984,       1985,       1986,       1987,       1988,
             1989,       1990,       1991,       1992,       1993,       1994,
             1995,       1996,       1997,       1998,       1999,       2000,
             2001,       2002,       2003,       2004,       2005,       2006,
             2007,       2008,       2009,       2010,       2011,       2012,
             2013],
      dtype='object')

In [16]:
df.columns.tolist()

['Type',
 'Coverage',
 'OdName',
 'AREA',
 'AreaName',
 'REG',
 'RegName',
 'DEV',
 'DevName',
 1980,
 1981,
 1982,
 1983,
 1984,
 1985,
 1986,
 1987,
 1988,
 1989,
 1990,
 1991,
 1992,
 1993,
 1994,
 1995,
 1996,
 1997,
 1998,
 1999,
 2000,
 2001,
 2002,
 2003,
 2004,
 2005,
 2006,
 2007,
 2008,
 2009,
 2010,
 2011,
 2012,
 2013]

In [17]:
df.drop([    'Type', 'Coverage',     'AREA',      'REG',  'DevName',], 
        axis = 1, 
        inplace = True
       )

In [18]:
df.rename(columns={"OdName":"Country","AreaName":"Continent"},
                   inplace=True
         )
df.head(2)

,Country,Continent,RegName,DEV,1980,1981,1982,1983,1984,1985,1986,1987,1988,1989,1990,1991,1992,1993,1994,1995,1996,1997,1998,1999,2000,2001,2002,2003,2004,2005,2006,2007,2008,2009,2010,2011,2012,2013
0,Afghanistan,Asia,Southern Asia,902,16,39,39,47,71,340,496,741,828,1076,1028,1378,1170,713,858,1537,2212,2555,1999,2395,3326,4067,3697,3479,2978,3436,3009,2652,2111,1746,1758,2203,2635,2004
1,Albania,Europe,Southern Europe,901,1,0,0,0,0,0,1,2,2,3,3,21,56,96,71,63,113,307,574,1264,1816,1602,1021,853,1450,1223,856,702,560,716,561,539,620,603

In [19]:
df.iloc[:,3]

0      902
1      901
2      902
3      902
4      901
5      902
6      902
7      902
8      902
9      901
10     901
11     902
12     902
13     902
14     902
15     902
16     901
17     901
18     902
19     902
20     902
21     902
22     901
23     902
24     902
25     902
26     901
27     902
28     902
29     902
30     902
31     902
32     901
33     902
34     902
35     902
36     902
37     902
38     902
39     902
40     902
41     902
42     902
43     902
44     901
45     902
46     902
47     901
48     902
49     902
50     901
51     902
52     902
53     902
54     902
55     902
56     902
57     902
58     902
59     901
60     902
61     902
62     901
63     901
64     902
65     902
66     902
67     901
68     902
69     901
70     902
71     902
72     902
73     902
74     902
75     902
76     902
77     901
78     901
79     902
80     902
81     902
82     902
83     901
84     902
85     901
86     902
87     901
88     902
89     902
90     902
91     902
92     902
93     902
94     902
95     901
96     902
97     902
98     902
99     902
100    901
101    901
102    901
103    902
104    902
105    902
106    902
107    902
108    901
109    902
110    902
111    902
112    902
113    901
114    902
115    901
116    902
117    902
118    902
119    902
120    902
121    902
122    901
123    902
124    901
125    902
126    902
127    902
128    901
129    902
130    902
131    902
132    902
133    902
134    902
135    902
136    902
137    901
138    901
139    902
140    902
141    901
142    901
143    901
144    902
145    902
146    902
147    902
148    902
149    901
150    902
151    902
152    902
153    901
154    902
155    902
156    902
157    901
158    901
159    902
160    902
161    901
162    902
163    902
164    902
165    902
166    902
167    901
168    901
169    902
170    902
171    902
172    901
173    902
174    902
175    902
176    902
177    902
178    902
179    902
180    902
181    901
182    902
183    901
184    902
185    901
186    902
187    902
188    902
189    902
190    902
191    902
192    902
193    902
194    902
Name: DEV, dtype: int64

# 1. How many people from Japan reached Canada during 1980 tp 2013?

In [20]:
df["Total"]=df.iloc[:,3:].sum(axis=1)

In [21]:
df.head()

,Country,Continent,RegName,DEV,1980,1981,1982,1983,1984,1985,1986,1987,1988,1989,1990,1991,1992,1993,1994,1995,1996,1997,1998,1999,2000,2001,2002,2003,2004,2005,2006,2007,2008,2009,2010,2011,2012,2013,Total
0,Afghanistan,Asia,Southern Asia,902,16,39,39,47,71,340,496,741,828,1076,1028,1378,1170,713,858,1537,2212,2555,1999,2395,3326,4067,3697,3479,2978,3436,3009,2652,2111,1746,1758,2203,2635,2004,59541
1,Albania,Europe,Southern Europe,901,1,0,0,0,0,0,1,2,2,3,3,21,56,96,71,63,113,307,574,1264,1816,1602,1021,853,1450,1223,856,702,560,716,561,539,620,603,16600
2,Algeria,Africa,Northern Africa,902,80,67,71,69,63,44,69,132,242,434,491,872,795,717,595,1106,2054,1842,2292,2389,2867,3418,3406,3072,3616,3626,4807,3623,4005,5393,4752,4325,3774,4331,70341
3,American Samoa,Oceania,Polynesia,902,0,1,0,0,0,0,0,1,0,1,2,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,908
4,Andorra,Europe,Southern Europe,901,0,0,0,0,0,0,2,0,0,0,3,0,1,0,0,0,0,0,2,0,0,1,0,2,0,0,1,1,0,0,0,0,1,1,916

# iloc[RowStart:RowEnd,ColumnStart:ColumnEnd]

In [22]:
df.set_index("Country", 
             inplace=True)
df

,Continent,RegName,DEV,1980,1981,1982,1983,1984,1985,1986,1987,1988,1989,1990,1991,1992,1993,1994,1995,1996,1997,1998,1999,2000,2001,2002,2003,2004,2005,2006,2007,2008,2009,2010,2011,2012,2013,Total
Country,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
Afghanistan,Asia,Southern Asia,902,16,39,39,47,71,340,496,741,828,1076,1028,1378,1170,713,858,1537,2212,2555,1999,2395,3326,4067,3697,3479,2978,3436,3009,2652,2111,1746,1758,2203,2635,2004,59541
Albania,Europe,Southern Europe,901,1,0,0,0,0,0,1,2,2,3,3,21,56,96,71,63,113,307,574,1264,1816,1602,1021,853,1450,1223,856,702,560,716,561,539,620,603,16600
Algeria,Africa,Northern Africa,902,80,67,71,69,63,44,69,132,242,434,491,872,795,717,595,1106,2054,1842,2292,2389,2867,3418,3406,3072,3616,3626,4807,3623,4005,5393,4752,4325,3774,4331,70341
American Samoa,Oceania,Polynesia,902,0,1,0,0,0,0,0,1,0,1,2,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,908
Andorra,Europe,Southern Europe,901,0,0,0,0,0,0,2,0,0,0,3,0,1,0,0,0,0,0,2,0,0,1,0,2,0,0,1,1,0,0,0,0,1,1,916
Angola,Africa,Middle Africa,902,1,3,6,6,4,3,5,5,11,6,8,23,26,22,8,26,38,27,58,49,70,169,168,165,268,295,184,106,76,62,61,39,70,45,3015
Antigua and Barbuda,Latin America and the Caribbean,Caribbean,902,0,0,0,0,42,52,51,61,34,51,31,59,61,44,18,23,21,27,19,12,13,25,17,25,14,24,32,15,32,38,27,37,51,25,1883
Argentina,Latin America and the Caribbean,South America,902,368,426,626,241,237,196,213,519,374,538,678,763,1023,1022,366,380,396,391,349,318,427,635,865,1745,1591,1153,847,620,540,467,459,278,263,282,20498
Armenia,Asia,Western Asia,902,0,0,0,0,0,0,0,0,0,0,0,0,22,21,66,75,102,115,89,112,124,87,132,153,147,224,218,198,205,267,252,236,258,207,4212
Australia,Oceania,Australia and New Zealand,901,702,639,484,317,317,319,356,467,410,553,620,640,734,886,702,668,699,623,479,523,599,799,747,876,930,909,875,1033,1018,1018,933,851,982,1121,24730
Austria,Europe,Western Europe,901,234,238,201,117,127,165,196,265,198,227,158,189,131,132,133,153,191,152,190,117,97,134,87,113,118,122,102,98,91,109,124,84,102,90,5886
Azerbaijan,Asia,Western Asia,902,0,0,0,0,0,0,0,0,0,0,0,0,0,17,18,23,26,38,62,54,77,98,186,167,230,359,236,203,125,165,209,138,161,57,3551
Bahamas,Latin America and the Caribbean,Caribbean,902,26,23,38,12,21,28,23,18,22,32,18,29,16,20,21,17,30,17,14,13,14,20,17,14,13,14,18,23,30,27,25,40,60,55,1710
Bahrain,Asia,Western Asia,902,0,2,1,1,1,3,0,2,10,9,6,9,9,11,14,10,17,28,14,27,34,13,17,15,12,12,12,22,9,35,28,21,39,32,1377
Bangladesh,Asia,Southern Asia,902,83,84,86,81,98,92,486,503,476,387,611,1115,1655,1280,1361,2042,2824,3378,2202,2064,3119,3831,2944,2137,2660,4171,4014,2897,2939,2104,4721,2694,2640,3789,66470
Barbados,Latin America and the Caribbean,Caribbean,902,372,376,299,244,265,285,251,303,265,275,327,373,336,380,179,211,176,153,139,114,122,148,122,74,90,111,97,130,134,125,121,97,132,97,7825
Belarus,Europe,Eastern Europe,901,0,0,0,0,0,0,0,0,0,0,0,0,12,40,114,118,156,349,540,426,515,430,435,435,543,558,439,568,524,454,438,357,277,247,8876
Belgium,Europe,Western Europe,901,511,540,519,297,183,181,197,283,333,307,303,216,208,240,201,240,279,227,307,209,369,340,307,320,411,400,302,363,335,358,363,332,402,379,11663
Belize,Latin America and the Caribbean,Central America,902,16,27,13,21,37,26,25,23,53,33,38,41,27,37,41,43,27,33,20,37,28,24,35,16,25,37,24,28,48,38,39,36,34,53,1985
Benin,Africa,Western Africa,902,2,5,4,3,4,3,6,4,20,14,13,13,25,25,18,15,29,32,19,37,35,66,71,78,112,95,116,183,205,238,290,284,391,397,3754
Bhutan,Asia,Southern Asia,902,0,0,0,0,1,0,0,0,0,1,0,2,2,1,1,4,2,2,1,3,6,6,8,7,1,5,10,7,36,865,1464,1879,1075,487,6778
Bolivia (Plurinational State of),Latin America and the Caribbean,South America,902,44,52,42,49,38,44,79,165,63,68,71,214,247,180,75,61,96,43,33,42,33,72,57,59,85,134,139,107,143,214,180,86,83,107,4107
Bosnia and Herzegovina,Europe,Southern Europe,901,0,0,0,0,0,0,0,0,0,0,0,0,258,2095,2090,3007,2599,2214,2789,2737,854,801,433,267,188,211,217,209,182,156,168,140,121,119,22756
Botswana,Africa,Southern Africa,902,10,1,3,3,7,4,2,3,8,8,2,2,4,4,0,2,3,2,0,2,3,2,4,4,9,7,11,8,28,15,42,53,64,76,1298
Brazil,Latin America and the Caribbean,South America,902,211,220,192,139,145,130,205,244,394,650,650,877,1066,866,566,572,586,591,531,626,845,847,745,839,917,969,1181,1746,2138,2509,2598,1508,1642,1714,30561
Brunei Darussalam,Asia,South-Eastern Asia,902,79,6,8,2,2,4,12,16,103,63,44,65,31,36,14,17,4,6,1,3,6,3,4,6,3,4,5,11,10,5,12,6,3,6,1502
Bulgaria,Europe,Eastern Europe,901,24,20,12,33,11,24,33,52,43,85,172,611,1116,965,687,762,825,732,779,832,1172,1283,1517,1507,2022,1738,1419,1172,994,784,556,365,451,512,24211
Burkina Faso,Africa,Western Africa,902,2,1,3,2,3,2,7,18,6,4,4,22,21,19,3,12,16,23,14,20,31,46,37,34,97,91,147,136,139,162,186,144,269,322,2945
Burundi,Africa,Eastern Africa,902,0,0,0,0,1,2,1,5,1,14,19,9,19,14,28,126,367,207,94,202,342,334,364,383,559,626,468,614,448,566,529,604,684,480,9012
Cabo Verde,Africa,Western Africa,902,1,1,2,0,11,1,9,3,1,7,14,16,15,11,9,4,7,16,9,3,4,5,2,13,3,5,7,2,5,1,3,3,6,2,1103
Cambodia,Asia,South-Eastern Asia,902,12,19,26,33,10,7,8,14,15,27,34,38,93,418,371,286,216,313,241,165,245,259,230,277,348,370,529,460,354,203,200,196,233,288,7440
Cameroon,Africa,Middle Africa,902,9,2,16,7,8,13,11,18,20,38,34,66,71,78,67,122,178,104,197,220,244,206,222,301,436,604,697,1025,1279,1344,1800,1638,2507,2439,16923
Canada,Northern America,Northern America,901,0,0,0,0,0,0,0,0,0,0,3,3,4,3,1,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,1,2,921
Central African Republic,Africa,Middle Africa,902,4,3,1,0,0,0,0,2,3,4,6,2,11,4,4,4,6,9,17,6,13,6,20,10,13,49,18,30,28,19,26,18,45,169,1452
Chad,Africa,Middle Africa,902,0,0,1,0,0,1,2,3,7,14,8,2,10,13,6,5,38,26,30,122,148,90,76,64,92,126,96,131,95,87,98,79,97,86,2555
Chile,Latin America and the Caribbean,South America,902,1233,1069,1078,781,681,533,633,1454,990,1023,1286,1749,1175,697,352,273,244,325,376,397,366,369,401,347,383,384,427,530,350,375,340,174,291,273,22261
China,Asia,Eastern Asia,902,5123,6682,3308,1863,1527,1816,1960,2643,2758,4323,8076,14255,10846,9817,13128,14398,19415,20475,21049,30069,35529,36434,31961,36439,36619,42584,33518,27642,30037,29622,30391,28502,33024,34129,660864
"China, Hong Kong Special Administrative Region",Asia,Eastern Asia,902,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,24,257,400,470,379,430,446,536,729,712,674,897,657,623,591,728,774,10229
"China, Macao Special Administrative Region",Asia,Eastern Asia,902,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,15,28,21,21,21,32,16,12,21,21,13,33,29,1186
Colombia,Latin America and the Caribbean,South America,902,266,326,360,244,235,214,257,376,352,439,614,652,582,464,375,371,381,578,929,1306,2259,2965,3283,4318,4566,6424,6535,5357,5452,4652,5218,4366,3741,3631,72990
Comoros,Africa,Eastern Africa,902,0,2,2,0,0,2,1,0,2,2,1,3,0,2,4,4,5,2,4,1,3,14,2,11,6,5,7,11,3,19,22,14,18,22,1096
Congo,Africa,Middle Africa,902,2,0,1,0,1,2,4,1,1,5,3,6,13,4,14,11,15,25,44,102,119,106,84,112,142,136,143,87,72,70,75,81,91,114,2588
Costa Rica,Latin America and the Caribbean,Central America,902,28,35,42,51,75,113,79,116,104,92,99,156,216,184,83,89,118,135,103,100,106,134,106,105,165,188,279,281,246,217,190,149,183,122,5391
Côte d'Ivoire,Africa,Western Africa,902,14,8,10,6,21,23,23,20,17,37,42,62,62,67,68,101,102,67,57,110,118,143,184,119,256,294,431,619,646,668,1066,636,1024,1170,9193
Croatia,Europe,Southern Europe,901,0,0,0,0,0,0,0,0,0,0,0,0,151,938,692,647,541,622,676,993,715,376,304,177,151,128,102,102,131,92,91,135,112,125,8902
Cuba,Latin America and the Caribbean,Caribbean,902,306,41,94,104,101,115,102,139,90,122,135,158,220,374,360,421,508,566,531,696,842,950,872,877,866,999,1064,1350,1300,1433,961,962,1304,1402,21267
Cyprus,Asia,Western Asia,902,132,128,84,46,46,43,48,48,56,55,27,37,29,42,24,16,31,36,19,15,16,22,13,17,11,7,9,4,7,6,18,6,12,16,2028
Czech Republic,Europe,Eastern Europe,901,0,0,0,0,0,0,0,0,0,0,0,1,0,107,155,128,149,182,206,524,470,290,226,181,191,193,146,137,104,159,168,128,173,174,5093
Democratic People's Republic of Korea,Asia,Eastern Asia,902,1,1,3,1,4,3,0,0,0,0,1,4,16,0,1,0,0,4,1,4,6,8,11,18,15,14,10,7,19,11,45,97,66,17,1290
Democratic Republic of the Congo,Africa,Middle Africa,902,15,16,17,17,28,11,38,66,46,48,116,223,439,404,309,529,796,663,768,937,1232,1248,1103,1233,1465,1521,1623,1466,1397,1581,1239,1224,1714,2050,26484
Denmark,Europe,Northern Europe,901,272,293,299,106,93,73,93,109,129,129,118,111,158,186,93,111,70,83,63,81,93,81,70,89,89,62,101,97,108,81,92,93,94,81,4802
Djibouti,Africa,Eastern Africa,902,0,1,1,5,1,0,4,2,4,6,10,14,34,23,10,13,19,28,30,85,145,96,62,43,67,93,68,50,47,70,123,127,164,201,2548
Dominica,Latin America and the Caribbean,Caribbean,902,104,81,94,65,81,79,50,89,75,96,77,127,125,106,57,77,66,68,56,67,72,82,62,65,50,59,72,79,60,59,43,36,43,48,3372
Dominican Republic,Latin America and the Caribbean,Caribbean,902,40,53,104,88,97,84,307,446,358,409,363,517,557,646,432,276,306,285,210,254,241,264,202,234,270,303,295,311,438,391,479,739,604,590,12095
Ecuador,Latin America and the Caribbean,South America,902,238,207,184,155,179,208,240,344,265,278,552,643,644,547,431,368,310,317,295,291,342,353,418,361,417,491,525,419,437,373,353,348,282,418,13135
Egypt,Africa,Northern Africa,902,612,660,755,455,447,348,514,1017,1085,1663,2365,1860,1558,1598,2375,2821,2561,2137,1387,1378,1642,2595,2039,2230,2393,2496,2190,2356,3347,3496,5982,4663,5555,4165,73647
El Salvador,Latin America and the Caribbean,Central America,902,110,295,882,2587,2666,2769,3106,3558,2720,2955,4384,7124,5670,2977,1217,722,736,603,477,424,569,453,473,446,442,436,430,929,1115,845,787,691,641,639,55780
Equatorial Guinea,Africa,Middle Africa,902,0,0,0,0,0,0,1,0,0,0,0,1,2,1,0,0,0,3,1,0,4,1,2,2,2,3,4,5,1,5,4,4,4,11,963
Eritrea,Africa,Eastern Africa,902,0,0,0,0,0,0,0,0,0,0,0,0,0,0,33,58,100,80,77,79,153,221,176,262,414,528,700,699,799,904,931,1182,1335,1719,11352
Estonia,Europe,Northern Europe,901,0,0,0,0,0,0,0,0,0,0,14,4,30,51,39,70,89,73,50,54,58,30,38,56,27,26,18,34,34,26,28,15,26,45,1836
Ethiopia,Africa,Eastern Africa,902,98,59,54,98,154,157,302,555,690,1096,890,1168,1876,1779,1204,870,999,739,563,678,1074,1062,818,1399,1535,1506,1801,1512,1613,1289,1865,2163,1864,1606,36038
Fiji,Oceania,Melanesia,902,632,705,814,554,389,446,361,523,561,736,1172,1619,1782,1317,1016,674,621,448,388,360,458,643,611,561,495,298,277,304,321,311,398,316,270,228,21511
Finland,Europe,Northern Europe,901,208,205,170,70,83,69,68,92,89,78,73,63,76,98,99,76,58,82,55,63,70,53,59,65,54,67,51,62,89,63,63,72,62,76,3682
France,Europe,Western Europe,901,1729,2027,2219,1490,1169,1177,1298,1658,2038,2332,2177,2911,3487,3709,2759,3332,2623,2473,3214,3343,3765,3806,3463,3568,4391,4429,4002,4290,4532,5051,4646,4080,6280,5623,109992
Gabon,Africa,Middle Africa,902,2,3,2,2,1,0,0,5,3,4,10,5,3,8,4,5,9,12,14,20,16,26,24,42,33,67,68,101,86,86,64,63,74,90,1854
Gambia,Africa,Western Africa,902,0,0,1,0,0,2,4,22,3,6,12,21,51,43,15,23,19,25,17,18,23,22,10,10,10,29,38,32,25,10,37,24,18,33,1505
Georgia,Asia,Western Asia,902,0,0,0,0,0,0,0,0,0,0,0,0,8,22,27,67,49,46,92,46,83,124,123,127,106,114,125,132,112,128,126,139,147,125,2970
Germany,Europe,Western Europe,901,1626,1977,3062,2376,1610,1441,1233,1704,1482,1706,1273,1273,1181,1488,1255,1553,1686,1397,1363,1717,1703,1456,1375,1865,2020,2226,2767,2449,3833,3887,2956,2053,1702,1217,64813
Ghana,Africa,Western Africa,902,172,196,98,122,116,172,215,970,408,429,449,1134,2502,2201,1341,1475,1219,1274,1040,845,959,782,696,564,738,851,710,688,629,659,802,528,531,517,26934
Greece,Europe,Southern Europe,901,1065,953,897,633,580,584,547,765,564,773,538,592,492,445,275,220,221,190,141,149,150,135,107,117,120,100,74,110,107,119,101,102,146,298,13311
Grenada,Latin America and the Caribbean,Caribbean,902,154,181,231,165,167,168,235,302,165,170,172,268,434,492,235,364,366,387,330,294,372,354,259,222,296,283,363,360,284,325,208,173,142,170,9993
Guatemala,Latin America and the Caribbean,Central America,902,114,108,113,366,598,975,1265,1060,702,773,1023,2156,1906,1392,757,640,655,519,358,287,329,269,242,179,217,190,230,258,263,264,266,288,358,345,20367
Guinea,Africa,Western Africa,902,0,3,3,6,4,3,5,14,12,17,10,44,36,32,16,49,61,38,107,100,168,177,205,196,281,256,342,415,327,347,395,352,407,463,5793
Guinea-Bissau,Africa,Western Africa,902,0,0,0,0,1,0,0,0,3,4,4,4,1,2,2,2,3,4,0,1,1,3,2,6,4,7,12,7,2,0,2,2,4,0,985
Guyana,Latin America and the Caribbean,South America,902,2334,2943,3575,2650,1932,2299,3942,6174,2977,3270,2824,3266,2932,3399,4181,3935,2324,1795,1238,1366,1308,1707,1479,1410,1341,1215,1286,1277,1137,1180,953,804,676,656,76687
Haiti,Latin America and the Caribbean,Caribbean,902,1666,3692,3498,2860,1418,1321,1753,2132,1829,2377,2379,2829,2399,3655,2100,2014,1955,1645,1295,1439,1631,2433,2174,1930,1652,1682,1619,1598,2491,2080,4744,6503,5868,4152,85715
Honduras,Latin America and the Caribbean,Central America,902,26,33,30,68,65,69,81,135,111,138,187,688,840,551,291,270,299,225,167,173,201,180,143,105,133,166,164,165,187,169,386,538,436,350,8672
Hungary,Europe,Eastern Europe,901,205,310,397,337,310,522,647,676,1139,979,780,775,795,603,349,306,364,319,337,408,418,627,537,489,671,516,520,425,383,312,354,287,300,425,17723
Iceland,Europe,Northern Europe,901,17,33,10,9,13,6,11,11,7,3,2,11,17,15,11,9,14,11,20,17,9,26,11,17,23,10,2,15,13,15,30,38,42,72,1471
India,Asia,Southern Asia,902,8880,8670,8147,7338,5704,4211,7150,10189,11522,10343,12041,13734,13673,21496,18620,18489,23859,22268,17241,18974,28572,31223,31889,27155,28235,36210,33848,28742,28261,29456,34235,27509,30933,33087,692806
Indonesia,Asia,South-Eastern Asia,902,186,178,252,115,123,100,127,213,270,260,227,252,243,278,262,205,231,166,165,525,1138,907,709,515,552,632,613,657,661,504,712,390,395,387,14052
Iran (Islamic Republic of),Asia,Southern Asia,902,1172,1429,1822,1592,1977,1648,1794,2989,3273,3781,3655,6250,6814,3959,2785,3956,6205,7982,7057,6208,5884,6169,8129,5918,6348,5837,7480,6974,6475,6580,7477,7479,7534,11291,176825
Iraq,Asia,Western Asia,902,262,245,260,380,428,231,265,384,619,911,557,1013,1498,2103,1500,2034,2675,2564,2037,2159,2591,2821,2432,1515,1796,2226,1788,2406,3543,5450,5941,6196,4041,4918,70691
Ireland,Europe,Northern Europe,901,781,895,707,298,327,287,481,1078,1415,1378,845,705,533,436,331,231,276,220,170,162,178,190,178,192,244,224,283,300,412,395,547,525,725,1015,17865
Israel,Asia,Western Asia,902,1403,1711,1334,541,446,680,1212,1497,1389,1762,1596,1358,1259,1584,1699,2224,2515,2998,3172,2387,2510,2436,2539,2314,2788,2446,2625,2401,2562,2316,2755,1970,2134,1945,67410
Italy,Europe,Southern Europe,901,1820,2057,1480,820,858,667,731,1101,885,1068,895,711,623,663,558,508,476,491,399,410,383,410,374,321,334,344,325,320,370,429,434,374,440,545,23525
Jamaica,Latin America and the Caribbean,Caribbean,902,3198,2634,2661,2455,2508,2938,4649,5415,3924,3946,4945,5056,5991,6065,3913,3619,3282,2847,2253,2358,2482,2838,2524,2054,2237,1945,1722,2141,2334,2456,2321,2059,2182,2479,107333
Japan,Asia,Eastern Asia,901,701,756,598,309,246,198,248,422,324,494,379,506,605,907,956,826,994,924,897,1083,1010,1092,806,817,973,1067,1212,1250,1284,1194,1168,1265,1214,982,28608
Jordan,Asia,Western Asia,902,177,160,155,113,102,179,181,392,489,785,841,807,909,1141,1173,1006,1070,1317,999,1218,1511,1904,1499,1614,1733,1940,1827,1421,1581,1235,1831,1635,1206,1255,36308
Kazakhstan,Asia,Central Asia,902,0,0,0,0,0,0,0,0,0,0,0,0,3,24,42,56,152,593,884,537,450,501,418,542,545,506,408,436,394,431,377,381,462,348,9392
Kenya,Africa,Eastern Africa,902,291,296,221,201,218,245,244,628,984,1140,869,605,529,478,414,434,369,223,203,310,495,651,630,678,685,693,622,449,453,489,507,585,725,664,18130
Kiribati,Oceania,Micronesia,902,0,0,0,1,0,0,0,0,0,2,0,0,0,1,0,1,1,0,2,0,1,1,0,0,0,1,0,0,1,1,0,0,2,0,917
Kuwait,Asia,Western Asia,902,1,0,8,2,1,4,4,9,19,19,26,31,96,109,99,130,187,108,121,80,114,107,74,72,74,66,35,62,53,68,67,58,73,48,2927
Kyrgyzstan,Asia,Central Asia,902,0,0,0,0,0,0,0,0,0,0,0,0,0,7,8,10,8,43,63,68,56,95,124,99,245,173,161,135,168,173,157,159,278,123,3255
Lao People's Democratic Republic,Asia,South-Eastern Asia,902,11,6,16,16,7,17,21,20,22,44,34,33,63,44,52,40,24,31,16,31,36,40,49,22,38,42,74,53,32,39,54,22,25,15,1991
Latvia,Europe,Northern Europe,901,0,0,0,0,0,0,1,0,0,0,10,17,23,47,80,73,67,123,119,127,130,175,156,110,94,77,69,88,67,85,70,103,202,213,3227
Lebanon,Asia,Western Asia,902,1409,1119,1159,789,1253,1683,2576,3803,3970,7157,13568,12567,6915,4902,2751,2228,1919,1472,1329,1594,1903,2578,2332,3179,3293,3709,3802,3467,3566,3077,3432,3072,1614,2172,116261
Lesotho,Africa,Southern Africa,902,1,1,1,2,7,5,3,1,6,5,1,4,4,7,2,3,9,2,1,4,1,0,2,2,2,4,0,4,1,8,7,1,0,6,1009
Liberia,Africa,Western Africa,902,1,2,2,1,4,4,3,4,3,7,5,11,52,37,40,55,59,61,28,36,56,60,57,139,409,581,356,153,74,94,162,106,58,39,3661
Libya,Africa,Northern Africa,902,5,7,9,24,10,31,23,81,43,77,47,86,89,85,74,116,128,156,113,157,208,228,210,153,196,196,281,198,306,282,384,352,299,255,5811
Liechtenstein,Europe,Western Europe,901,1,4,2,0,0,3,0,1,1,1,0,1,2,3,1,0,7,2,0,2,0,2,0,1,0,1,0,0,1,1,0,2,1,0,941
Lithuania,Europe,Northern Europe,901,1,1,0,0,0,1,0,0,1,1,5,11,43,63,84,103,87,114,74,96,116,183,125,194,220,167,113,108,109,63,57,52,77,145,3315
Luxembourg,Europe,Western Europe,901,14,4,2,5,1,3,6,2,4,8,1,3,1,18,9,1,7,9,3,1,5,5,17,9,9,10,9,9,3,5,8,11,6,7,1116
Madagascar,Africa,Eastern Africa,902,22,10,13,32,30,18,10,42,36,27,28,37,34,55,16,30,35,56,48,34,32,57,59,48,79,88,96,115,118,169,178,148,165,229,3096
Malawi,Africa,Eastern Africa,902,5,4,6,3,2,0,4,7,1,4,10,9,4,12,6,5,6,11,8,14,12,5,7,3,17,23,15,13,5,10,28,16,9,10,1196
Malaysia,Asia,South-Eastern Asia,902,786,816,813,448,384,374,425,817,2072,2346,1917,1338,1486,1000,727,490,382,319,214,299,360,460,480,419,401,593,580,600,658,640,802,409,358,204,25319
Maldives,Asia,Southern Asia,902,0,0,0,1,0,0,0,0,0,0,0,0,3,3,0,0,0,0,1,0,1,0,1,0,1,0,0,2,1,7,4,3,1,1,932
Mali,Africa,Western Africa,902,4,4,7,3,3,4,3,5,4,7,13,31,90,51,35,36,67,26,43,30,66,67,62,72,87,87,114,143,154,164,170,155,191,190,3090
Malta,Europe,Southern Europe,901,191,242,153,64,60,68,76,78,111,68,38,29,28,12,10,15,21,12,15,13,10,24,16,28,28,28,24,7,21,18,17,8,9,4,2447
Marshall Islands,Oceania,Micronesia,902,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,2,0,0,0,0,0,0,904
Mauritania,Africa,Western Africa,902,5,0,3,3,1,1,1,4,3,6,4,5,7,8,6,3,10,11,6,11,15,30,27,23,60,86,124,96,112,83,74,54,77,57,1918
Mauritius,Africa,Eastern Africa,902,306,259,353,170,207,164,325,578,531,399,401,358,336,276,176,147,159,136,159,138,199,393,348,566,702,696,512,507,714,872,1455,1146,799,1203,16592
Mexico,Latin America and the Caribbean,Central America,902,409,394,491,490,509,425,667,813,916,1017,1193,1134,1189,1139,776,758,1234,1689,1379,1679,1662,1939,1894,1754,2259,2837,2844,3239,2856,3092,3865,3947,4227,3996,59614
Monaco,Europe,Western Europe,901,0,0,0,0,0,1,0,1,0,1,3,0,0,3,1,1,1,0,0,0,1,1,1,1,1,1,1,1,0,0,4,1,3,1,930
Mongolia,Asia,Eastern Asia,902,0,0,0,0,0,0,0,0,0,0,1,1,1,0,1,1,8,1,0,1,17,17,20,28,34,59,64,82,59,118,169,103,68,99,1854
Montenegro,Europe,Southern Europe,901,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,7,19,10,14,19,26,9,1006
Morocco,Africa,Northern Africa,902,325,471,447,335,248,328,388,505,685,1060,1313,1390,1055,1042,660,1069,939,1095,1262,1870,2664,4067,4174,3369,3686,2939,3322,4021,4226,5532,6242,4399,3878,3261,73169
Mozambique,Africa,Eastern Africa,902,0,0,7,2,3,1,3,1,5,5,3,6,6,8,3,5,1,2,8,8,3,2,5,3,8,5,9,5,5,12,7,3,4,12,1062
Myanmar,Asia,South-Eastern Asia,902,80,62,46,31,41,23,18,33,55,77,133,104,62,100,172,199,229,205,68,98,121,113,164,263,191,210,953,1887,975,1153,556,368,193,262,10147
Namibia,Africa,Southern Africa,902,0,5,5,3,2,1,1,4,3,2,2,4,0,5,0,9,2,0,0,4,9,9,10,7,9,6,19,13,26,14,16,23,24,83,1222
Nauru,Oceania,Micronesia,902,1,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,1,1,3,2,4,1,1,1,0,0,1,0,0,0,1,920
Nepal,Asia,Southern Asia,902,1,1,6,1,2,4,13,6,13,4,23,29,32,40,31,66,132,155,104,157,236,272,363,313,404,607,540,511,581,561,1392,1129,1185,1308,11124

In [23]:
df.index.name=None

In [24]:
df.loc["Japan"]

Continent            Asia
RegName      Eastern Asia
DEV                   901
1980                  701
1981                  756
1982                  598
1983                  309
1984                  246
1985                  198
1986                  248
1987                  422
1988                  324
1989                  494
1990                  379
1991                  506
1992                  605
1993                  907
1994                  956
1995                  826
1996                  994
1997                  924
1998                  897
1999                 1083
2000                 1010
2001                 1092
2002                  806
2003                  817
2004                  973
2005                 1067
2006                 1212
2007                 1250
2008                 1284
2009                 1194
2010                 1168
2011                 1265
2012                 1214
2013                  982
Total               28608
Name: Japan, dtype: object

# Conclusion 

 In total 27707 people emmigrates from Japan to Canada

In [25]:
df.columns = list(map(str,df.columns))
df.columns

Index(['Continent', 'RegName', 'DEV', '1980', '1981', '1982', '1983', '1984',
       '1985', '1986', '1987', '1988', '1989', '1990', '1991', '1992', '1993',
       '1994', '1995', '1996', '1997', '1998', '1999', '2000', '2001', '2002',
       '2003', '2004', '2005', '2006', '2007', '2008', '2009', '2010', '2011',
       '2012', '2013', 'Total'],
      dtype='object')

In [26]:
type(df.loc["Japan"])

pandas.core.series.Series

In [27]:
df.iloc[87]

Continent            Asia
RegName      Eastern Asia
DEV                   901
1980                  701
1981                  756
1982                  598
1983                  309
1984                  246
1985                  198
1986                  248
1987                  422
1988                  324
1989                  494
1990                  379
1991                  506
1992                  605
1993                  907
1994                  956
1995                  826
1996                  994
1997                  924
1998                  897
1999                 1083
2000                 1010
2001                 1092
2002                  806
2003                  817
2004                  973
2005                 1067
2006                 1212
2007                 1250
2008                 1284
2009                 1194
2010                 1168
2011                 1265
2012                 1214
2013                  982
Total               28608
Name: Japan, dtype: object

In [28]:
df[df.index=="Mexico"]

,Continent,RegName,DEV,1980,1981,1982,1983,1984,1985,1986,1987,1988,1989,1990,1991,1992,1993,1994,1995,1996,1997,1998,1999,2000,2001,2002,2003,2004,2005,2006,2007,2008,2009,2010,2011,2012,2013,Total
Mexico,Latin America and the Caribbean,Central America,902,409,394,491,490,509,425,667,813,916,1017,1193,1134,1189,1139,776,758,1234,1689,1379,1679,1662,1939,1894,1754,2259,2837,2844,3239,2856,3092,3865,3947,4227,3996,59614

In [29]:
df.loc["Japan", "2000"]

1010

In [30]:
df.loc["Japan", ["2000", "2010"]]

2000    1010
2010    1168
Name: Japan, dtype: object

# Data filtering based on criteria

In [31]:
condition=df["Continent"]=="Asia"
print(condition)

Afghanistan                                              True
Albania                                                 False
Algeria                                                 False
American Samoa                                          False
Andorra                                                 False
Angola                                                  False
Antigua and Barbuda                                     False
Argentina                                               False
Armenia                                                  True
Australia                                               False
Austria                                                 False
Azerbaijan                                               True
Bahamas                                                 False
Bahrain                                                  True
Bangladesh                                               True
Barbados                                                False
Belarus                                                 False
Belgium                                                 False
Belize                                                  False
Benin                                                   False
Bhutan                                                   True
Bolivia (Plurinational State of)                        False
Bosnia and Herzegovina                                  False
Botswana                                                False
Brazil                                                  False
Brunei Darussalam                                        True
Bulgaria                                                False
Burkina Faso                                            False
Burundi                                                 False
Cabo Verde                                              False
Cambodia                                                 True
Cameroon                                                False
Canada                                                  False
Central African Republic                                False
Chad                                                    False
Chile                                                   False
China                                                    True
China, Hong Kong Special Administrative Region           True
China, Macao Special Administrative Region               True
Colombia                                                False
Comoros                                                 False
Congo                                                   False
Costa Rica                                              False
Côte d'Ivoire                                           False
Croatia                                                 False
Cuba                                                    False
Cyprus                                                   True
Czech Republic                                          False
Democratic People's Republic of Korea                    True
Democratic Republic of the Congo                        False
Denmark                                                 False
Djibouti                                                False
Dominica                                                False
Dominican Republic                                      False
Ecuador                                                 False
Egypt                                                   False
El Salvador                                             False
Equatorial Guinea                                       False
Eritrea                                                 False
Estonia                                                 False
Ethiopia                                                False
Fiji                                                    False
Finland                                                 False
France                                                  False
Gabon                                                   False
Gambia                                                  False
Georgia                                                  True
Germany                                                 False
Ghana                                                   False
Greece                                                  False
Grenada                                                 False
Guatemala                                               False
Guinea                                                  False
Guinea-Bissau                                           False
Guyana                                                  False
Haiti                                                   False
Honduras                                                False
Hungary                                                 False
Iceland                                                 False
India                                                    True
Indonesia                                                True
Iran (Islamic Republic of)                               True
Iraq                                                     True
Ireland                                                 False
Israel                                                   True
Italy                                                   False
Jamaica                                                 False
Japan                                                    True
Jordan                                                   True
Kazakhstan                                               True
Kenya                                                   False
Kiribati                                                False
Kuwait                                                   True
Kyrgyzstan                                               True
Lao People's Democratic Republic                         True
Latvia                                                  False
Lebanon                                                  True
Lesotho                                                 False
Liberia                                                 False
Libya                                                   False
Liechtenstein                                           False
Lithuania                                               False
Luxembourg                                              False
Madagascar                                              False
Malawi                                                  False
Malaysia                                                 True
Maldives                                                 True
Mali                                                    False
Malta                                                   False
Marshall Islands                                        False
Mauritania                                              False
Mauritius                                               False
Mexico                                                  False
Monaco                                                  False
Mongolia                                                 True
Montenegro                                              False
Morocco                                                 False
Mozambique                                              False
Myanmar                                                  True
Namibia                                                 False
Nauru                                                   False
Nepal                                                    True
Netherlands                                             False
New Caledonia                                           False
New Zealand                                             False
Nicaragua                                               False
Niger                                                   False
Nigeria                                                 False
Norway                                                  False
Oman                                                     True
Pakistan                                                 True
Palau                                                   False
Panama                                                  False
Papua New Guinea                                        False
Paraguay                                                False
Peru                                                    False
Philippines                                              True
Poland                                                  False
Portugal                                                False
Qatar                                                    True
Republic of Korea                                        True
Republic of Moldova                                     False
Romania                                                 False
Russian Federation                                      False
Rwanda                                                  False
Saint Kitts and Nevis                                   False
Saint Lucia                                             False
Saint Vincent and the Grenadines                        False
Samoa                                                   False
San Marino                                              False
Sao Tome and Principe                                   False
Saudi Arabia                                             True
Senegal                                                 False
Serbia                                                  False
Seychelles                                              False
Sierra Leone                                            False
Singapore                                                True
Slovakia                                                False
Slovenia                                                False
Somalia                                                 False
South Africa                                            False
Spain                                                   False
Sri Lanka                                                True
State of Palestine                                       True
Sudan                                                   False
Suriname                                                False
Swaziland                                               False
Sweden                                                  False
Switzerland                                             False
Syrian Arab Republic                                     True
Tajikistan                                               True
Thailand                                                 True
The former Yugoslav Republic of Macedonia               False
Togo                                                    False
Tonga                                                   False
Trinidad and Tobago                                     False
Tunisia                                                 False
Turkey                                                   True
Turkmenistan                                             True
Tuvalu                                                  False
Uganda                                                  False
Ukraine                                                 False
United Arab Emirates                                     True
United Kingdom of Great Britain and Northern Ireland    False
United Republic of Tanzania                             False
United States of America                                False
Uruguay                                                 False
Uzbekistan                                               True
Vanuatu                                                 False
Venezuela (Bolivarian Republic of)                      False
Viet Nam                                                 True
Western Sahara                                          False
Yemen                                                    True
Zambia                                                  False
Zimbabwe                                                False
Name: Continent, dtype: bool

In [32]:
df[condition]

,Continent,RegName,DEV,1980,1981,1982,1983,1984,1985,1986,1987,1988,1989,1990,1991,1992,1993,1994,1995,1996,1997,1998,1999,2000,2001,2002,2003,2004,2005,2006,2007,2008,2009,2010,2011,2012,2013,Total
Afghanistan,Asia,Southern Asia,902,16,39,39,47,71,340,496,741,828,1076,1028,1378,1170,713,858,1537,2212,2555,1999,2395,3326,4067,3697,3479,2978,3436,3009,2652,2111,1746,1758,2203,2635,2004,59541
Armenia,Asia,Western Asia,902,0,0,0,0,0,0,0,0,0,0,0,0,22,21,66,75,102,115,89,112,124,87,132,153,147,224,218,198,205,267,252,236,258,207,4212
Azerbaijan,Asia,Western Asia,902,0,0,0,0,0,0,0,0,0,0,0,0,0,17,18,23,26,38,62,54,77,98,186,167,230,359,236,203,125,165,209,138,161,57,3551
Bahrain,Asia,Western Asia,902,0,2,1,1,1,3,0,2,10,9,6,9,9,11,14,10,17,28,14,27,34,13,17,15,12,12,12,22,9,35,28,21,39,32,1377
Bangladesh,Asia,Southern Asia,902,83,84,86,81,98,92,486,503,476,387,611,1115,1655,1280,1361,2042,2824,3378,2202,2064,3119,3831,2944,2137,2660,4171,4014,2897,2939,2104,4721,2694,2640,3789,66470
Bhutan,Asia,Southern Asia,902,0,0,0,0,1,0,0,0,0,1,0,2,2,1,1,4,2,2,1,3,6,6,8,7,1,5,10,7,36,865,1464,1879,1075,487,6778
Brunei Darussalam,Asia,South-Eastern Asia,902,79,6,8,2,2,4,12,16,103,63,44,65,31,36,14,17,4,6,1,3,6,3,4,6,3,4,5,11,10,5,12,6,3,6,1502
Cambodia,Asia,South-Eastern Asia,902,12,19,26,33,10,7,8,14,15,27,34,38,93,418,371,286,216,313,241,165,245,259,230,277,348,370,529,460,354,203,200,196,233,288,7440
China,Asia,Eastern Asia,902,5123,6682,3308,1863,1527,1816,1960,2643,2758,4323,8076,14255,10846,9817,13128,14398,19415,20475,21049,30069,35529,36434,31961,36439,36619,42584,33518,27642,30037,29622,30391,28502,33024,34129,660864
"China, Hong Kong Special Administrative Region",Asia,Eastern Asia,902,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,24,257,400,470,379,430,446,536,729,712,674,897,657,623,591,728,774,10229
"China, Macao Special Administrative Region",Asia,Eastern Asia,902,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,15,28,21,21,21,32,16,12,21,21,13,33,29,1186
Cyprus,Asia,Western Asia,902,132,128,84,46,46,43,48,48,56,55,27,37,29,42,24,16,31,36,19,15,16,22,13,17,11,7,9,4,7,6,18,6,12,16,2028
Democratic People's Republic of Korea,Asia,Eastern Asia,902,1,1,3,1,4,3,0,0,0,0,1,4,16,0,1,0,0,4,1,4,6,8,11,18,15,14,10,7,19,11,45,97,66,17,1290
Georgia,Asia,Western Asia,902,0,0,0,0,0,0,0,0,0,0,0,0,8,22,27,67,49,46,92,46,83,124,123,127,106,114,125,132,112,128,126,139,147,125,2970
India,Asia,Southern Asia,902,8880,8670,8147,7338,5704,4211,7150,10189,11522,10343,12041,13734,13673,21496,18620,18489,23859,22268,17241,18974,28572,31223,31889,27155,28235,36210,33848,28742,28261,29456,34235,27509,30933,33087,692806
Indonesia,Asia,South-Eastern Asia,902,186,178,252,115,123,100,127,213,270,260,227,252,243,278,262,205,231,166,165,525,1138,907,709,515,552,632,613,657,661,504,712,390,395,387,14052
Iran (Islamic Republic of),Asia,Southern Asia,902,1172,1429,1822,1592,1977,1648,1794,2989,3273,3781,3655,6250,6814,3959,2785,3956,6205,7982,7057,6208,5884,6169,8129,5918,6348,5837,7480,6974,6475,6580,7477,7479,7534,11291,176825
Iraq,Asia,Western Asia,902,262,245,260,380,428,231,265,384,619,911,557,1013,1498,2103,1500,2034,2675,2564,2037,2159,2591,2821,2432,1515,1796,2226,1788,2406,3543,5450,5941,6196,4041,4918,70691
Israel,Asia,Western Asia,902,1403,1711,1334,541,446,680,1212,1497,1389,1762,1596,1358,1259,1584,1699,2224,2515,2998,3172,2387,2510,2436,2539,2314,2788,2446,2625,2401,2562,2316,2755,1970,2134,1945,67410
Japan,Asia,Eastern Asia,901,701,756,598,309,246,198,248,422,324,494,379,506,605,907,956,826,994,924,897,1083,1010,1092,806,817,973,1067,1212,1250,1284,1194,1168,1265,1214,982,28608
Jordan,Asia,Western Asia,902,177,160,155,113,102,179,181,392,489,785,841,807,909,1141,1173,1006,1070,1317,999,1218,1511,1904,1499,1614,1733,1940,1827,1421,1581,1235,1831,1635,1206,1255,36308
Kazakhstan,Asia,Central Asia,902,0,0,0,0,0,0,0,0,0,0,0,0,3,24,42,56,152,593,884,537,450,501,418,542,545,506,408,436,394,431,377,381,462,348,9392
Kuwait,Asia,Western Asia,902,1,0,8,2,1,4,4,9,19,19,26,31,96,109,99,130,187,108,121,80,114,107,74,72,74,66,35,62,53,68,67,58,73,48,2927
Kyrgyzstan,Asia,Central Asia,902,0,0,0,0,0,0,0,0,0,0,0,0,0,7,8,10,8,43,63,68,56,95,124,99,245,173,161,135,168,173,157,159,278,123,3255
Lao People's Democratic Republic,Asia,South-Eastern Asia,902,11,6,16,16,7,17,21,20,22,44,34,33,63,44,52,40,24,31,16,31,36,40,49,22,38,42,74,53,32,39,54,22,25,15,1991
Lebanon,Asia,Western Asia,902,1409,1119,1159,789,1253,1683,2576,3803,3970,7157,13568,12567,6915,4902,2751,2228,1919,1472,1329,1594,1903,2578,2332,3179,3293,3709,3802,3467,3566,3077,3432,3072,1614,2172,116261
Malaysia,Asia,South-Eastern Asia,902,786,816,813,448,384,374,425,817,2072,2346,1917,1338,1486,1000,727,490,382,319,214,299,360,460,480,419,401,593,580,600,658,640,802,409,358,204,25319
Maldives,Asia,Southern Asia,902,0,0,0,1,0,0,0,0,0,0,0,0,3,3,0,0,0,0,1,0,1,0,1,0,1,0,0,2,1,7,4,3,1,1,932
Mongolia,Asia,Eastern Asia,902,0,0,0,0,0,0,0,0,0,0,1,1,1,0,1,1,8,1,0,1,17,17,20,28,34,59,64,82,59,118,169,103,68,99,1854
Myanmar,Asia,South-Eastern Asia,902,80,62,46,31,41,23,18,33,55,77,133,104,62,100,172,199,229,205,68,98,121,113,164,263,191,210,953,1887,975,1153,556,368,193,262,10147
Nepal,Asia,Southern Asia,902,1,1,6,1,2,4,13,6,13,4,23,29,32,40,31,66,132,155,104,157,236,272,363,313,404,607,540,511,581,561,1392,1129,1185,1308,11124
Oman,Asia,Western Asia,902,0,0,0,8,0,0,0,3,0,1,5,0,5,1,12,11,2,7,4,3,7,12,7,11,12,14,18,16,10,7,14,10,13,11,1126
Pakistan,Asia,Southern Asia,902,978,972,1201,900,668,514,691,1072,1334,2261,2470,3079,4071,4777,4666,4994,9125,13073,9068,9979,15400,16708,15110,13205,13399,14314,13127,10124,8994,7217,6811,7468,11227,12603,242502
Philippines,Asia,South-Eastern Asia,902,6051,5921,5249,4562,3801,3150,4166,7360,8639,11865,12509,12718,13670,20479,19532,15864,13692,11549,8735,9734,10763,13836,11707,12758,14004,18139,18400,19837,24887,28573,38617,36765,34315,29544,512293
Qatar,Asia,Western Asia,902,0,0,0,0,0,0,1,0,1,0,2,6,5,3,2,4,4,7,3,7,4,21,4,4,5,11,2,5,9,6,18,3,14,6,1059
Republic of Korea,Asia,Eastern Asia,902,1011,1456,1572,1081,847,962,1208,2338,2805,2979,2087,2598,3790,3819,3005,3501,3250,4093,4938,7108,7618,9619,7342,7117,5352,5832,6215,5920,7294,5874,5537,4588,5316,4509,143483
Saudi Arabia,Asia,Western Asia,902,0,0,1,4,1,2,5,7,29,41,22,47,71,55,43,40,84,78,71,74,89,98,71,70,128,198,252,188,249,246,330,278,286,267,4327
Singapore,Asia,South-Eastern Asia,902,241,301,337,169,128,139,205,372,808,1269,843,657,492,474,375,407,409,287,231,437,444,473,588,391,311,392,298,690,734,366,805,219,146,141,15481
Sri Lanka,Asia,Southern Asia,902,185,371,290,197,1086,845,1838,4447,2779,2758,3525,7266,13102,9563,7150,9368,6484,5415,3566,4982,6081,5861,5279,4892,4495,4930,4714,4123,4756,4547,4422,3309,3338,2394,149260
State of Palestine,Asia,Western Asia,902,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,8,26,146,180,238,343,266,323,376,453,627,441,481,400,654,555,533,462,7414
Syrian Arab Republic,Asia,Western Asia,902,315,419,409,269,264,385,493,927,864,1454,1791,1596,1172,1247,965,1053,942,859,892,823,924,1067,956,1085,1116,1458,1145,1056,919,917,1039,1005,650,1009,32387
Tajikistan,Asia,Central Asia,902,0,0,0,0,0,0,0,0,0,0,0,0,0,5,5,5,2,11,4,4,5,20,9,7,14,85,46,44,15,50,52,47,34,39,1405
Thailand,Asia,South-Eastern Asia,902,56,53,113,65,82,66,78,117,147,177,171,219,219,279,237,172,195,152,201,246,258,309,547,439,392,575,500,487,519,512,499,396,296,400,10076
Turkey,Asia,Western Asia,902,481,874,706,280,338,202,257,397,346,488,767,941,1116,1316,908,732,638,679,777,806,1101,1184,1301,1338,1736,2065,1638,1463,1122,1238,1492,1257,1068,729,32683
Turkmenistan,Asia,Central Asia,902,0,0,0,0,0,0,0,0,0,0,0,0,0,1,1,0,10,6,4,2,7,10,11,22,16,40,26,37,13,20,30,20,20,14,1212
United Arab Emirates,Asia,Western Asia,902,0,2,2,1,2,0,5,4,1,17,7,23,27,11,13,8,33,27,25,24,27,41,37,32,41,31,42,37,33,37,86,60,54,46,1738
Uzbekistan,Asia,Central Asia,902,0,0,0,0,0,0,0,0,0,0,0,0,12,44,33,34,58,75,97,106,101,102,144,155,175,330,262,284,215,288,289,162,235,167,4270
Viet Nam,Asia,South-Eastern Asia,902,1191,1829,2162,3404,7583,5907,2741,1406,1411,3004,3801,5870,5416,6547,5105,3723,2462,1752,1631,1419,1803,2117,2291,1713,1816,1852,3153,2574,1784,2171,1942,1723,1731,2112,98048
Yemen,Asia,Western Asia,902,1,2,1,6,0,18,7,12,7,18,4,18,41,41,39,73,144,121,141,134,122,181,171,113,124,161,140,122,133,128,211,160,174,217,3887

In [33]:
df[condition & (df["RegName"]=="Southern Asia")]

,Continent,RegName,DEV,1980,1981,1982,1983,1984,1985,1986,1987,1988,1989,1990,1991,1992,1993,1994,1995,1996,1997,1998,1999,2000,2001,2002,2003,2004,2005,2006,2007,2008,2009,2010,2011,2012,2013,Total
Afghanistan,Asia,Southern Asia,902,16,39,39,47,71,340,496,741,828,1076,1028,1378,1170,713,858,1537,2212,2555,1999,2395,3326,4067,3697,3479,2978,3436,3009,2652,2111,1746,1758,2203,2635,2004,59541
Bangladesh,Asia,Southern Asia,902,83,84,86,81,98,92,486,503,476,387,611,1115,1655,1280,1361,2042,2824,3378,2202,2064,3119,3831,2944,2137,2660,4171,4014,2897,2939,2104,4721,2694,2640,3789,66470
Bhutan,Asia,Southern Asia,902,0,0,0,0,1,0,0,0,0,1,0,2,2,1,1,4,2,2,1,3,6,6,8,7,1,5,10,7,36,865,1464,1879,1075,487,6778
India,Asia,Southern Asia,902,8880,8670,8147,7338,5704,4211,7150,10189,11522,10343,12041,13734,13673,21496,18620,18489,23859,22268,17241,18974,28572,31223,31889,27155,28235,36210,33848,28742,28261,29456,34235,27509,30933,33087,692806
Iran (Islamic Republic of),Asia,Southern Asia,902,1172,1429,1822,1592,1977,1648,1794,2989,3273,3781,3655,6250,6814,3959,2785,3956,6205,7982,7057,6208,5884,6169,8129,5918,6348,5837,7480,6974,6475,6580,7477,7479,7534,11291,176825
Maldives,Asia,Southern Asia,902,0,0,0,1,0,0,0,0,0,0,0,0,3,3,0,0,0,0,1,0,1,0,1,0,1,0,0,2,1,7,4,3,1,1,932
Nepal,Asia,Southern Asia,902,1,1,6,1,2,4,13,6,13,4,23,29,32,40,31,66,132,155,104,157,236,272,363,313,404,607,540,511,581,561,1392,1129,1185,1308,11124
Pakistan,Asia,Southern Asia,902,978,972,1201,900,668,514,691,1072,1334,2261,2470,3079,4071,4777,4666,4994,9125,13073,9068,9979,15400,16708,15110,13205,13399,14314,13127,10124,8994,7217,6811,7468,11227,12603,242502
Sri Lanka,Asia,Southern Asia,902,185,371,290,197,1086,845,1838,4447,2779,2758,3525,7266,13102,9563,7150,9368,6484,5415,3566,4982,6081,5861,5279,4892,4495,4930,4714,4123,4756,4547,4422,3309,3338,2394,149260

In [34]:
nDf= df[condition & (df["RegName"]=="Southern Asia")]

In [35]:
nDf.describe()

,DEV,1980,1981,1982,1983,1984,1985,1986,1987,1988,1989,1990,1991,1992,1993,1994,1995,1996,1997,1998,1999,2000,2001,2002,2003,2004,2005,2006,2007,2008,2009,2010,2011,2012,2013,Total
count,9.0,9.000000,9.000000,9.000000,9.000000,9.000000,9.000000,9.000000,9.000000,9.000000,9.000000,9.000000,9.000000,9.000000,9.000000,9.000000,9.000000,9.000000,9.000000,9.000000,9.000000,9.000000,9.000000,9.000000,9.000000,9.000000,9.000000,9.000000,9.000000,9.000000,9.000000,9.000000,9.000000,9.000000,9.000000,9.000000
mean,902.0,1257.222222,1285.111111,1287.888889,1128.555556,1067.444444,850.444444,1385.333333,2216.333333,2247.222222,2290.111111,2594.777778,3650.333333,4502.444444,4648.000000,3941.333333,4495.111111,5649.222222,6092.000000,4582.111111,4973.555556,6958.333333,7570.777778,7491.111111,6345.111111,6502.333333,7723.333333,7415.777778,6225.777778,6017.111111,5898.111111,6920.444444,5963.666667,6729.777778,7440.444444,156248.666667
std,0.0,2893.967207,2815.988922,2652.848160,2392.058481,1865.123194,1371.195839,2275.046868,3359.087674,3681.604093,3318.478132,3835.785766,4652.671356,5514.502224,7068.730774,6022.220853,6071.190234,7572.348790,7447.755232,5721.584712,6228.434697,9422.046925,10258.422512,10347.614284,8839.858249,9170.842437,11549.637851,10762.734118,9090.364759,8886.109827,9213.858644,10561.196536,8486.970028,9744.632584,10658.809409,218158.237930
min,902.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,2.000000,1.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,1.000000,0.000000,1.000000,0.000000,1.000000,0.000000,0.000000,2.000000,1.000000,7.000000,4.000000,3.000000,1.000000,1.000000,932.000000
25%,902.0,1.000000,1.000000,6.000000,1.000000,2.000000,4.000000,13.000000,6.000000,13.000000,4.000000,23.000000,29.000000,32.000000,40.000000,31.000000,66.000000,132.000000,155.000000,104.000000,157.000000,236.000000,272.000000,363.000000,313.000000,404.000000,607.000000,540.000000,511.000000,581.000000,865.000000,1464.000000,1879.000000,1185.000000,1308.000000,11124.000000
50%,902.0,83.000000,84.000000,86.000000,81.000000,98.000000,340.000000,496.000000,741.000000,828.000000,1076.000000,1028.000000,1378.000000,1655.000000,1280.000000,1361.000000,2042.000000,2824.000000,3378.000000,2202.000000,2395.000000,3326.000000,4067.000000,3697.000000,3479.000000,2978.000000,4171.000000,4014.000000,2897.000000,2939.000000,2104.000000,4422.000000,2694.000000,2640.000000,2394.000000,66470.000000
75%,902.0,978.000000,972.000000,1201.000000,900.000000,1086.000000,845.000000,1794.000000,2989.000000,2779.000000,2758.000000,3525.000000,6250.000000,6814.000000,4777.000000,4666.000000,4994.000000,6484.000000,7982.000000,7057.000000,6208.000000,6081.000000,6169.000000,8129.000000,5918.000000,6348.000000,5837.000000,7480.000000,6974.000000,6475.000000,6580.000000,6811.000000,7468.000000,7534.000000,11291.000000,176825.000000
max,902.0,8880.000000,8670.000000,8147.000000,7338.000000,5704.000000,4211.000000,7150.000000,10189.000000,11522.000000,10343.000000,12041.000000,13734.000000,13673.000000,21496.000000,18620.000000,18489.000000,23859.000000,22268.000000,17241.000000,18974.000000,28572.000000,31223.000000,31889.000000,27155.000000,28235.000000,36210.000000,33848.000000,28742.000000,28261.000000,29456.000000,34235.000000,27509.000000,30933.000000,33087.000000,692806.000000

# Create a Dataframe

In [36]:
df1 =pd.DataFrame({"a":[1,3,5,7,9],
                 "b":["one","three","five","seven","nine"]
                }
                )
df1

   a      b
0  1    one
1  3  three
2  5   five
3  7  seven
4  9   nine

In [37]:
df2=pd.DataFrame({"c":[2,4,6,7,9],
                "d":["two", "four", "six", "seven", "nine"]
                 }
                )
df2

   c      d
0  2    two
1  4   four
2  6    six
3  7  seven
4  9   nine

In [38]:
df3 = pd.concat([df1,df2],
               axis = 1
               )
df3

   a      b  c      d
0  1    one  2    two
1  3  three  4   four
2  5   five  6    six
3  7  seven  7  seven
4  9   nine  9   nine

In [39]:
df4= pd.concat([df1,df2],
               axis=0
              )
df4

     a      b    c      d
0  1.0    one  NaN    NaN
1  3.0  three  NaN    NaN
2  5.0   five  NaN    NaN
3  7.0  seven  NaN    NaN
4  9.0   nine  NaN    NaN
0  NaN    NaN  2.0    two
1  NaN    NaN  4.0   four
2  NaN    NaN  6.0    six
3  NaN    NaN  7.0  seven
4  NaN    NaN  9.0   nine

In [40]:
x=pd.DataFrame ({"a":[2, np.nan,3,8],
                 "b":[4,5,7,8],
                 "c":[2,4,np.nan,8]
                }
               )
x

     a  b    c
0  2.0  4  2.0
1  NaN  5  4.0
2  3.0  7  NaN
3  8.0  8  8.0

In [41]:
df1= x
df2= x
df3= x

In [47]:
df1.dropna(axis=0)
df1

     a  b    c
0  2.0  4  2.0
1  NaN  5  4.0
2  3.0  7  NaN
3  8.0  8  8.0

In [46]:
df2.dropna(axis=1)
df2

     a  b    c
0  2.0  4  2.0
1  NaN  5  4.0
2  3.0  7  NaN
3  8.0  8  8.0

In [48]:
df3

     a  b    c
0  2.0  4  2.0
1  NaN  5  4.0
2  3.0  7  NaN
3  8.0  8  8.0

In [49]:
df3.dropna()

     a  b    c
0  2.0  4  2.0
3  8.0  8  8.0

In [50]:
df3

     a  b    c
0  2.0  4  2.0
1  NaN  5  4.0
2  3.0  7  NaN
3  8.0  8  8.0

In [56]:
df4.loc["Total"]=df4.sum(numeric_only=True,
                       axis=0)

In [57]:
df4

          a      b     c      d
0       1.0    one   NaN    NaN
1       3.0  three   NaN    NaN
2       5.0   five   NaN    NaN
3       7.0  seven   NaN    NaN
4       9.0   nine   NaN    NaN
0       NaN    NaN   2.0    two
1       NaN    NaN   4.0   four
2       NaN    NaN   6.0    six
3       NaN    NaN   7.0  seven
4       NaN    NaN   9.0   nine
Total  25.0    NaN  28.0    NaN